name: Build LaTeX documents

on:
  push

jobs:
  build_paper:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Build Winter/310B
        uses: cvxgrp/.github/actions/latex@main
        with:
          paper: Winter/310B/STATS*.tex
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          output-folder: /Winter/310B

      
      - name: Build Winter/305B
        uses: cvxgrp/.github/actions/latex@main
        with:
          paper: Winter/305B/STATS*.tex
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          output-folder: /Winter/305B

      - name: Build Winter/300B
        uses: cvxgrp/.github/actions/latex@main
        with:
          paper: Winter/300B/STATS*.tex
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          output-folder: /Winter/300B

      - name: Build Fall/310A
        uses: cvxgrp/.github/actions/latex@main
        with:
          paper: Fall/310A/STATS*.tex
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          output-folder: /Fall/310A

      - name: Build Fall/305A
        uses: cvxgrp/.github/actions/latex@main
        with:
          paper: Fall/305A/STATS*.tex
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          output-folder: /Fall/305A

      - name: Build Fall/300A
        uses: cvxgrp/.github/actions/latex@main
        with:
          paper: Fall/300A/STATS*.tex
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          output-folder: /Fall/300A
      
