name: Build LaTeX documents

on:
  push

jobs:
  build_paper:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Build Winter/310B
        uses: cvxgrp/.github/actions/latex@main
        with:
          paper: Winter/310B/STATS*.tex
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          output-folder: /Winter/310B

      # One file does not properly compile and requires a revisit
      #- name: Build Winter/305B
      #  uses: cvxgrp/.github/actions/latex@main
      #  with:
      #    paper: Winter/305B/STATS*.tex
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #    output-folder: /Winter/305B